version: "3.9"

services:
  auth_service:
    build:
      context: ./chatty_auth_service
    expose:
      - "8000"
    volumes:
      - ./chatty_auth_service:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  post_service:
    build:
      context: ./chatty_post_service
    expose:
      - "8001"
    volumes:
      - ./chatty_post_service:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  subscription_service:
    build:
      context: ./chatty_subscription_service
    expose:
      - "8002"
    volumes:
      - ./chatty_subscription_service:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  admin_service:
    build:
      context: ./chatty_admin_service
    expose:
      - "8003"
    volumes:
      - ./chatty_admin_service:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  recommendation_service:
    build:
      context: ./chatty_recommendation_service
    expose:
      - "8004"
    volumes:
      - ./chatty_recommendation_service:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=chatty_user
      - POSTGRES_PASSWORD=chatty_pass
      - POSTGRES_DB=chatty_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --host http://nginx:80
    depends_on:
      - nginx

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - post_service
      - subscription_service
      - admin_service
      - recommendation_service

volumes:
  postgres_data:

