global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "chatty_services"
    static_configs:
      - targets:
          - "auth_service:8000"
          - "post_service:8001"
          - "subscription_service:8002"
          - "admin_service:8003"
          - "recommendation_service:8004"