name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r chatty_auth_service/requirements.txt
          pip install -r chatty_post_service/requirements.txt
          pip install -r chatty_subscription_service/requirements.txt
          pip install -r chatty_admin_service/requirements.txt
          pip install -r chatty_recommendation_service/requirements.txt

      - name: Run tests
        run: |
          pytest chatty_auth_service/tests/
          pytest chatty_post_service/tests/
          pytest chatty_subscription_service/tests/
          pytest chatty_admin_service/tests/
          pytest chatty_recommendation_service/tests/

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$SERVER_IP << 'EOF'
            mkdir -p ~/chatty
            cd ~/chatty
            git pull origin main || git clone https://github.com/<your-username>/ChattyMicroservices.git .
            docker-compose down
            docker-compose up -d --build
          EOF
